Step 1: Create the SQLite Database

In [1]:
import sqlite3
import pandas as pd 

conn=sqlite3.connect("automobile_market.db")

Step 2: Load the Cleaned Dataset

In [2]:
df=pd.read_csv('cleaned_vehicle_sales.csv')
df.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,...,sellingprice,saledate,vehicle_age,price_difference,price_ratio,sale_year,sale_month,sale_day,sale_weekday,sale_quarter
0,2015,Kia,Sorento,LX,Suv,Automatic,5xyktca69fg566472,ca,5.0,16639.0,...,21500.0,2014-12-16 04:30:00+00:00,-1,1000.0,1.048780,2014,December,16,Tuesday,4
1,2015,Kia,Sorento,LX,Suv,Automatic,5xyktca69fg561319,ca,5.0,9393.0,...,21500.0,2014-12-16 04:30:00+00:00,-1,700.0,1.033654,2014,December,16,Tuesday,4
2,2014,Bmw,3 Series,328i SULEV,Sedan,Automatic,wba3c1c51ek116351,ca,45.0,1331.0,...,30000.0,2015-01-14 20:30:00+00:00,1,-1900.0,0.940439,2015,January,14,Wednesday,1
3,2015,Volvo,S60,T5,Sedan,Automatic,yv1612tb4f1310987,ca,41.0,14282.0,...,27750.0,2015-01-28 20:30:00+00:00,0,250.0,1.009091,2015,January,28,Wednesday,1
4,2014,Bmw,6 Series Gran Coupe,650i,Sedan,Automatic,wba6b2c57ed129731,ca,43.0,2641.0,...,67000.0,2014-12-18 04:30:00+00:00,0,1000.0,1.015152,2014,December,18,Thursday,4

Step 3: Create the SQL Table

In [3]:
df.to_sql(
    "vehicle_sales",
    conn,
    if_exists="replace",
    index=False
)

558799

Table is created automatically and all the data has been loaded.

STEP 4 — Data Validation

Query 1 Total Records

In [4]:
pd.read_sql("""
            select count(*) as Total_Records
            from vehicle_sales;
            """, conn)

   Total_Records
0         558799

Query 2 Number of Columns

In [5]:
pd.read_sql("""
            pragma table_info("vehicle_sales");""",conn)

    cid              name     type  notnull dflt_value  pk
0     0              year  INTEGER        0       None   0
1     1              make     TEXT        0       None   0
2     2             model     TEXT        0       None   0
3     3              trim     TEXT        0       None   0
4     4              body     TEXT        0       None   0
5     5      transmission     TEXT        0       None   0
6     6               vin     TEXT        0       None   0
7     7             state     TEXT        0       None   0
8     8         condition     REAL        0       None   0
9     9          odometer     REAL        0       None   0
10   10             color     TEXT        0       None   0
11   11          interior     TEXT        0       None   0
12   12            seller     TEXT        0       None   0
13   13               mmr     REAL        0       None   0
14   14      sellingprice     REAL        0       None   0
15   15          saledate     TEXT        0       None   0
16   16       vehicle_age  INTEGER        0       None   0
17   17  price_difference     REAL        0       None   0
18   18       price_ratio     REAL        0       None   0
19   19         sale_year  INTEGER        0       None   0
20   20        sale_month     TEXT        0       None   0
21   21          sale_day  INTEGER        0       None   0
22   22      sale_weekday     TEXT        0       None   0
23   23      sale_quarter  INTEGER        0       None   0

Query 3 First 10 Records

In [6]:
pd.read_sql("""
select * from vehicle_sales
limit 10;""",conn)

,year,make,model,trim,body,transmission,vin,state,condition,odometer,...,sellingprice,saledate,vehicle_age,price_difference,price_ratio,sale_year,sale_month,sale_day,sale_weekday,sale_quarter
0,2015,Kia,Sorento,LX,Suv,Automatic,5xyktca69fg566472,ca,5.0,16639.0,...,21500.0,2014-12-16 04:30:00+00:00,-1,1000.0,1.048780,2014,December,16,Tuesday,4
1,2015,Kia,Sorento,LX,Suv,Automatic,5xyktca69fg561319,ca,5.0,9393.0,...,21500.0,2014-12-16 04:30:00+00:00,-1,700.0,1.033654,2014,December,16,Tuesday,4
2,2014,Bmw,3 Series,328i SULEV,Sedan,Automatic,wba3c1c51ek116351,ca,45.0,1331.0,...,30000.0,2015-01-14 20:30:00+00:00,1,-1900.0,0.940439,2015,January,14,Wednesday,1
3,2015,Volvo,S60,T5,Sedan,Automatic,yv1612tb4f1310987,ca,41.0,14282.0,...,27750.0,2015-01-28 20:30:00+00:00,0,250.0,1.009091,2015,January,28,Wednesday,1
4,2014,Bmw,6 Series Gran Coupe,650i,Sedan,Automatic,wba6b2c57ed129731,ca,43.0,2641.0,...,67000.0,2014-12-18 04:30:00+00:00,0,1000.0,1.015152,2014,December,18,Thursday,4
5,2015,Nissan,Altima,2.5 S,Sedan,Automatic,1n4al3ap1fn326013,ca,1.0,5554.0,...,10900.0,2014-12-30 04:00:00+00:00,-1,-4450.0,0.710098,2014,December,30,Tuesday,4
6,2014,Bmw,M5,Base,Sedan,Automatic,wbsfv9c51ed593089,ca,34.0,14943.0,...,65000.0,2014-12-17 04:30:00+00:00,0,-4000.0,0.942029,2014,December,17,Wednesday,4
7,2014,Chevrolet,Cruze,1LT,Sedan,Automatic,1g1pc5sb2e7128460,ca,2.0,28617.0,...,9800.0,2014-12-16 05:00:00+00:00,0,-2100.0,0.823529,2014,December,16,Tuesday,4
8,2014,Audi,A4,2.0T Premium Plus quattro,Sedan,Automatic,wauffafl3en030343,ca,42.0,9557.0,...,32250.0,2014-12-18 04:00:00+00:00,0,150.0,1.004673,2014,December,18,Thursday,4
9,2014,Chevrolet,Camaro,LT,Convertible,Automatic,2g1fb3d37e9218789,ca,3.0,4809.0,...,17500.0,2015-01-19 20:00:00+00:00,1,-8800.0,0.665399,2015,January,19,Monday,1

Query 4 Distinct Brands

In [7]:
pd.read_sql("""select count(distinct make )from vehicle_sales;""",conn)

   count(distinct make )
0                     66

Query 5 Distinct States

In [8]:
pd.read_sql("""
            select count(distinct state) from vehicle_sales;""",conn)

   count(distinct state)
0                     38

STEP 6 — Executive KPI Analysis

KPI 1

Total Vehicles

In [9]:
pd.read_sql("""
            select count(*) as Total_Vehicles from vehicle_sales;""", conn)

   Total_Vehicles
0          558799

KPI 2 

Total Revenue

In [10]:
pd.read_sql(""" 
            select round(sum(sellingprice),2) as Total_Revenue from vehicle_sales;""", conn)

   Total_Revenue
0   7.606012e+09

KPI 3

Average Selling Price

In [11]:
pd.read_sql("""
            select round(avg(sellingprice),2)as Average_Selling_Price from vehicle_sales;""",conn)

   Average_Selling_Price
0               13611.36

KPI 4

Average MMR

In [12]:
pd.read_sql("""   
            select round(avg(mmr),2 ) as Average_MMR from vehicle_sales;""", conn)

   Average_MMR
0     13769.38

KPI 5

Average Vehicle Age

In [13]:
pd.read_sql("""
            select round(avg(vehicle_age),2) as Avg_Vehicle_Age from vehicle_sales""", conn)

   Avg_Vehicle_Age
0             4.87

KPI 6

Average Odometer

In [14]:
pd.read_sql("""
            select round(avg(odometer),2) as Avg_Odometer from vehicle_sales""", conn)

   Avg_Odometer
0      68321.13

KPI 7

Average Price Ratio

In [15]:
pd.read_sql("""
            select round(avg(price_ratio),2) as Avg_Price_Ratio from vehicle_sales""", conn)

   Avg_Price_Ratio
0             0.99

KPI 8

Average Price Difference

In [16]:
pd.read_sql("""
            select round(avg(price_difference),2) as Avg_price_difference from vehicle_sales""", conn)

   Avg_price_difference
0               -158.02

Step 7 . Market Analysis

1. Top 10 Brands

In [17]:
pd.read_sql("""
            select make,
            count(*) Vehicles from vehicle_sales
            group by make
            order by Vehicles desc
            limit 10;""", conn)

        make  Vehicles
0       Ford    104297
1  Chevrolet     60587
2     Nissan     54017
3     Toyota     39966
4      Dodge     30953
5      Honda     27351
6    Hyundai     21831
7        Bmw     20793
8        Kia     18082
9   Chrysler     17483

2. Top 10 Body

In [18]:
pd.read_sql("""
            select body,
            count(*) Vehicles
            from vehicle_sales as Top10_Body
            group by body
            order by Vehicles Desc
            limit 10;""", conn)

          body  Vehicles
0        Sedan    254527
1          Suv    143844
2    Hatchback     26237
3      Minivan     25529
4        Coupe     17752
5     Crew Cab     16394
6        Wagon     16128
7  Convertible     10476
8    Supercrew      9033
9      G Sedan      7417

3. Top 10 Seller

In [19]:
pd.read_sql("""
            select seller,
            count(*)Vehicles
            from vehicle_sales
            group by seller
            order by Vehicles desc
            limit 10;""", conn)

                                  seller  Vehicles
0                     nissan-infiniti lt     19693
1          ford motor credit company llc     19162
2                  the hertz corporation     18299
3                     santander consumer     15285
4                       avis corporation     12540
5                     nissan infiniti lt      9962
6            wells fargo dealer services      8796
7                       tdaf remarketing      7209
8         enterprise veh exchange/rental      6853
9  ge fleet services for itself/servicer      6692

4. Top Models

In [20]:
pd.read_sql("""
            select model,
            count(*) Sales
            from vehicle_sales
            group by model
            order by Sales desc;""", conn)

      model  Sales
0    Altima  29748
1     F-150  14479
2    Fusion  12945
3     Camry  12545
4    Escape  11861
..      ...    ...
968     350      1
969    328i      1
970    323i      1
971    320i      1
972       1      1

[973 rows x 2 columns]

5. Transmission Preference

In [21]:
pd.read_sql("""
            select transmission,
            count(*) Vehicles
            from vehicle_sales
            group by transmission
            order by Vehicles desc
            ;""", conn)

  transmission  Vehicles
0    Automatic    475904
1      Unknown     65351
2       Manual     17544

6. Vehicle Condidion Distribution

In [22]:
pd.read_sql("""
            select condition,
            count(*)Vehicles
            from vehicle_sales
            group by condition
            order by condition desc
            ;""", conn)

    condition  Vehicles
0        49.0     13099
1        48.0     12712
2        47.0     11363
3        46.0     12634
4        45.0     12313
5        44.0     25514
6        43.0     24937
7        42.0     24328
8        41.0     23073
9        39.0     19920
10       38.0     18723
11       37.0     25938
12       36.0     23144
13       35.0     38544
14       34.0     17397
15       33.0     10619
16       32.0      9962
17       31.0      9222
18       29.0     18928
19       28.0     19177
20       27.0     16350
21       26.0     11911
22       25.0     12559
23       24.0      9326
24       23.0      8188
25       22.0      6057
26       21.0      9199
27       19.0     42276
28       18.0       323
29       17.0       243
30       16.0       178
31       15.0       144
32       14.0       134
33       13.0        82
34       12.0        95
35       11.0        87
36        5.0     11222
37        4.0     19922
38        3.0     10802
39        2.0     20790
40        1.0      7364

Step 8. Pricing Analysis

1. Highest Average Price Brand

In [23]:
pd.read_sql("""
            select make, 
            round(avg(sellingprice),2) as Avg_price
            from vehicle_sales
            group by make
            order by Avg_price desc
            limit 15;""", conn)

             make  Avg_price
0     Rolls-Royce  153488.24
1         Ferrari  127210.53
2     Lamborghini  112625.00
3         Bentley   74367.67
4       Airstream   71000.00
5           Tesla   67054.35
6    Aston Martin   54812.00
7          Fisker   46461.11
8        Maserati   44947.06
9           Lotus   40800.00
10        Porsche   39842.94
11     Land Rover   31617.81
12            Ram   25299.94
13  Mercedes-Benz   21590.57
14            Bmw   21474.03

2. Highest Average Price Body

In [24]:
pd.read_sql("""
            select body,
            avg(sellingprice)as Avg_price
            from vehicle_sales
            group by body
            order by Avg_price Desc
            limit 15;""", conn)

                       body     Avg_price
0   Granturismo Convertible  76326.923077
1               Cts-V Wagon  50500.000000
2               Cts-V Coupe  38682.028571
3           Q60 Convertible  36577.380952
4                 Q60 Coupe  29661.111111
5                  Mega Cab  28966.216216
6               Crewmax Cab  26459.292035
7             G Convertible  26261.764706
8               Transit Van  23823.684211
9                Double Cab  23161.790756
10                Cts Coupe  22981.012658
11      Promaster Cargo Van  22840.677966
12                  G Coupe  22437.727558
13                Supercrew  22098.393003
14                 Crew Cab  21649.048859

3. Vehicles Sold Above MMR

In [25]:
pd.read_sql("""
             select count(*) from vehicle_sales
             where sellingprice>mmr;""", conn)

   count(*)
0    261161

4. Vehicles Sold Below MMR

In [26]:
pd.read_sql("""
            select count(*) from vehicle_sales
            where sellingprice < mmr;""", conn)

   count(*)
0    286415

5. Average Price Ratio By Brand

In [27]:
pd.read_sql("""
            select make, round(avg(price_ratio),2) as avg_ratio
            from vehicle_sales
            group by make
            order by avg_ratio desc;""", conn)

          make  avg_ratio
0    Airstream       2.41
1     Mercedes       1.22
2     Mazda Tk       1.21
3    Gmc Truck       1.18
4   Hyundai Tk       1.12
..         ...        ...
61         Geo       0.89
62    Dodge Tk       0.88
63     Ford Tk       0.81
64      Daewoo       0.73
65         Dot       0.59

[66 rows x 2 columns]

6. Highest Price Difference

In [28]:
pd.read_sql("""
            select
            make,
            model,
            trim,
            sellingprice,
            mmr,
            price_difference
            from vehicle_sales
            order by price_difference desc
            limit 20;""", conn)

,make,model,trim,sellingprice,mmr,price_difference
0,Ford,Escape,Titanium,230000.0,22800.0,207200.0
1,Ford,Escape,XLT,108200.0,8250.0,99950.0
2,Nissan,Versa,1.8 S,67500.0,10350.0,57150.0
3,Toyota,Corolla,LE,68900.0,15250.0,53650.0
4,Mercedes-Benz,Sprinter,2500 170 WB Cargo,84000.0,31900.0,52100.0
5,Bmw,4 Series,435i,84500.0,42500.0,42000.0
6,Airstream,interstate,rvb,71000.0,29500.0,41500.0
7,Chevrolet,Suburban,LTZ,55000.0,15300.0,39700.0
8,Bmw,Altima,650i xDrive,88500.0,51000.0,37500.0
9,Chevrolet,Suburban,LT,46400.0,11100.0,35300.0
10,Ford,Fusion,SE,49000.0,15200.0,33800.0
11,Bmw,3 Series,335i,79000.0,45300.0,33700.0
12,Ford,Mustang,GT,58600.0,26800.0,31800.0
13,Ford,F-250 Super Duty,Lariat,49900.0,18900.0,31000.0
14,Gmc,Savana,LS 1500,37000.0,6525.0,30475.0
15,Bmw,X1,xDrive28i,60000.0,29700.0,30300.0
16,Bmw,5 Series,528i,65700.0,35500.0,30200.0
17,Mercedes-Benz,S-Class,S550,109000.0,81000.0,28000.0
18,Bmw,5 Series,535i,79000.0,51400.0,27600.0
19,Mazda,Tribute,s,35000.0,8500.0,26500.0

7. Most Under Valued brands

In [29]:
pd.read_sql("""
            select make,
            round(avg(price_ratio),2) as Price_ratio 
            from vehicle_sales
            group by make
            order by Price_ratio
            limit 10;""", conn)

         make  Price_ratio
0         Dot         0.59
1      Daewoo         0.73
2     Ford Tk         0.81
3    Dodge Tk         0.88
4         Geo         0.89
5  Ford Truck         0.91
6      Fisker         0.95
7  Mercedes-B         0.96
8     Pontiac         0.96
9    Plymouth         0.97

Step 9. Seller Analysis

1. Top Sellers

In [30]:
pd.read_sql("""
            select seller,
            count(*) Vehicles
            from vehicle_sales
            group by seller
            order by Vehicles desc
            limit 15;""", conn)

                                    seller  Vehicles
0                       nissan-infiniti lt     19693
1            ford motor credit company llc     19162
2                    the hertz corporation     18299
3                       santander consumer     15285
4                         avis corporation     12540
5                       nissan infiniti lt      9962
6              wells fargo dealer services      8796
7                         tdaf remarketing      7209
8           enterprise veh exchange/rental      6853
9    ge fleet services for itself/servicer      6692
10                   hyundai motor finance      6660
11                jpmorgan chase bank n.a.      6235
12    ahfc/honda lease trust/hvt  inc. eot      6069
13  financial services remarketing (lease)      6009
14        mercedes-benz financial services      5658

2. Highest Revenue Seller

In [31]:
pd.read_sql("""
            select seller,
            round(sum(sellingprice),2) as Revenue
            from vehicle_sales
            group by seller
            order by Revenue desc 
            limit 15;""", conn)

                                    seller      Revenue
0            ford motor credit company llc  340960125.0
1                       nissan-infiniti lt  272104560.0
2                    the hertz corporation  250863168.0
3                       nissan infiniti lt  216158321.0
4                         avis corporation  203432330.0
5   financial services remarketing (lease)  174601400.0
6         mercedes-benz financial services  152773950.0
7           enterprise veh exchange/rental  126287886.0
8                       santander consumer  121287115.0
9                         tdaf remarketing  116104600.0
10                lexus financial services  100226700.0
11            r hollenshead auto sales inc   96529350.0
12                       avis budget group   87746350.0
13                   hyundai motor finance   86389000.0
14    ahfc/honda lease trust/hvt  inc. eot   85677875.0

3. Premium Sellers

In [32]:
pd.read_sql("""
            select
            seller,
            avg(sellingprice)as Avg_price
            from vehicle_sales
            group by seller
            order by Avg_price desc
            limit 10;""",conn)

                                            seller      Avg_price
0                                phelps auto sales  161000.000000
1         financial services remarketing (bmw int)  153222.222222
2                               autolink sales llc  134500.000000
3                                   chings trading  134000.000000
4                           carbiz solutions  inc.  133000.000000
5                        exotic motors corporation  119000.000000
6                                the car store inc  116000.000000
7                              go right auto group  115000.000000
8  porsche fin svcs dba bentley financial services  114142.857143
9                                  bryans cars.com  107000.000000

Step 10. Geographic Analysis

1. Sales By State

In [33]:
pd.read_sql("""
            select state,
            count(*) Vehicles
            from vehicle_sales
            group by state
            order by Vehicles desc;""", conn)

   state  Vehicles
0     fl     82945
1     ca     73148
2     pa     53907
3     tx     45913
4     ga     34750
5     nj     27784
6     il     23478
7     nc     21845
8     oh     21575
9     tn     20895
10    mo     16013
11    mi     15511
12    nv     12685
13    va     12025
14    md     11157
15    wi      9851
16    mn      9429
17    az      8740
18    co      7775
19    wa      7416
20    ma      6729
21    ny      5699
22    in      4325
23    sc      4251
24    ne      4013
25    on      3442
26    pr      2725
27    la      2191
28    ms      1851
29    ut      1836
30    qc      1245
31    hi      1237
32    or      1155
33    ab       928
34    nm       171
35    ok        72
36    ns        61
37    al        26

2. Revenue By State

In [34]:
pd.read_sql("""
            select state,
            sum(sellingprice) as Revenue
            from vehicle_sales
            group by state
            order by Revenue desc;""",conn)

   state       Revenue
0     fl  1.151065e+09
1     ca  1.061078e+09
2     pa  8.612346e+08
3     tx  6.064954e+08
4     ga  4.489274e+08
5     nj  3.781154e+08
6     tn  3.554186e+08
7     il  3.472900e+08
8     oh  3.108228e+08
9     mo  2.316471e+08
10    mi  2.309001e+08
11    nv  1.915152e+08
12    nc  1.891986e+08
13    wi  1.379488e+08
14    mn  1.292545e+08
15    co  1.234499e+08
16    wa  1.034190e+08
17    va  1.031112e+08
18    az  1.009105e+08
19    md  8.267062e+07
20    ny  6.482348e+07
21    on  6.131105e+07
22    ne  5.045528e+07
23    in  4.634485e+07
24    ma  4.526425e+07
25    sc  4.389656e+07
26    pr  2.564435e+07
27    la  2.305286e+07
28    ut  2.215249e+07
29    ms  2.081288e+07
30    qc  1.654975e+07
31    hi  1.508005e+07
32    or  1.335005e+07
33    ab  1.036765e+07
34    nm  1.075900e+06
35    ns  6.230000e+05
36    ok  4.981000e+05
37    al  2.377000e+05

3. Highest Average Selling Price BY state

In [35]:
pd.read_sql("""
            select state,
            round(avg(sellingprice),2) as Avg_Price
            from vehicle_sales
            group by state
            order by Avg_Price desc;""",conn)

   state  Avg_Price
0     on   17812.62
1     tn   17009.74
2     pa   15976.30
3     co   15877.80
4     nv   15097.77
5     mi   14886.22
6     il   14792.15
7     ca   14505.90
8     mo   14466.19
9     oh   14406.62
10    wi   14003.53
11    wa   13945.39
12    fl   13877.44
13    mn   13708.19
14    nj   13609.10
15    qc   13292.97
16    tx   13209.67
17    ga   12918.77
18    ne   12572.96
19    hi   12190.82
20    ut   12065.63
21    or   11558.48
22    az   11545.82
23    ny   11374.54
24    ms   11244.13
25    ab   11172.04
26    in   10715.57
27    la   10521.62
28    sc   10326.17
29    ns   10213.11
30    pr    9410.77
31    al    9142.31
32    nc    8660.96
33    va    8574.74
34    md    7409.75
35    ok    6918.06
36    ma    6726.74
37    nm    6291.81

4. Premium Vehicles By State

In [36]:
pd.read_sql("""
            select state,
            count(*) PremiumVehicle
            from vehicle_sales
            where sellingprice> 50000
            group by state
            order by PremiumVehicle desc;""",conn)

   state  PremiumVehicle
0     ca             992
1     fl             584
2     pa             438
3     oh             279
4     ga             230
5     tx             212
6     nj             202
7     nv             132
8     tn              91
9     wi              56
10    il              55
11    co              35
12    mo              27
13    mi              26
14    wa              19
15    nc              14
16    mn               6
17    md               6
18    la               6
19    ma               5
20    az               5
21    ne               4
22    va               3
23    ny               3
24    sc               2
25    on               2
26    ut               1
27    pr               1
28    ms               1
29    in               1

Step 11. Time Analysis

1. Monthly Sales

In [37]:
pd.read_sql("""
            select sale_month,
            count(*) Sales
            from vehicle_sales
            group by sale_month
            order by Sales desc;""", conn)

  sale_month   Sales
0   February  163053
1    January  140815
2       June   99276
3   December   53520
4        May   53098
5      March   46342
6      April    1438
7       July    1257

2. Quarterly Sales

In [38]:
pd.read_sql("""
            select sale_quarter,
            count(*) Sales
            from vehicle_sales
            group by sale_quarter
            order by Sales desc;""", conn)

   sale_quarter   Sales
0             1  350210
1             2  153812
2             4   53520
3             3    1257

3. weekday sales

In [39]:
pd.read_sql("""
            select sale_weekday,
            count(*) Sales
            from vehicle_sales
            group by sale_weekday
            order by Sales desc;""", conn)

  sale_weekday   Sales
0      Tuesday  180158
1    Wednesday  146363
2       Monday  131290
3     Thursday   77892
4       Sunday   11868
5       Friday   11228

4. average Sellinng Price by month

In [40]:
pd.read_sql("""
            select sale_month,
            round(avg(sellingprice),2) as Avg_sales
            from vehicle_sales
            group by sale_month
            order by Avg_sales desc;""", conn)

  sale_month  Avg_sales
0       July   17049.18
1       June   15033.57
2        May   14306.79
3   February   13608.23
4      March   13440.82
5    January   13291.77
6   December   11293.61
7      April   10149.54

Step 12. Premium Vehicle Analysis

1. Luxury Brands

In [41]:
pd.read_sql("""   
            select make,
            count(*) Vehicles
            from vehicle_sales
            where sellingprice>50000
            group by make
            order by Vehicles desc;""",conn)

             make  Vehicles
0             Bmw       725
1   Mercedes-Benz       620
2         Porsche       503
3       Chevrolet       319
4      Land Rover       192
5            Ford       166
6           Lexus       137
7            Audi       135
8         Bentley        92
9          Jaguar        86
10       Infiniti        78
11       Cadillac        66
12       Maserati        62
13         Nissan        61
14            Gmc        53
15           Jeep        28
16         Toyota        24
17          Tesla        22
18        Ferrari        19
19    Rolls-Royce        17
20   Aston Martin        15
21            Ram         5
22    Lamborghini         4
23        Lincoln         3
24        Hyundai         2
25         Fisker         2
26          Dodge         1
27      Airstream         1

2. Luxury Sellers

In [42]:
pd.read_sql("""   
            select seller,
            count(*) Vehicles
            from vehicle_sales
            where sellingprice>50000
            group by seller
            order by Vehicles desc;""",conn)

                                     seller  Vehicles
0          mercedes-benz financial services       210
1    financial services remarketing (lease)       182
2                porsche financial services       180
3                 bmw na manheim new jersey       150
4              r hollenshead auto sales inc       134
..                                      ...       ...
740    action finance & leasing corporation         1
741                               aatc auto         1
742                 aaero sweet corporation         1
743                    a.n.a auto sales llc         1
744                1 cochran of monroeville         1

[745 rows x 2 columns]

Step 13. Window Functions

1. Rank Vehicles

In [43]:
pd.read_sql("""
            select 
            make,
            model,
            trim,
            sellingprice,
            rank() over(
            order by sellingprice desc) 
            as PriceRank
            from vehicle_sales;""", conn)

                 make             model        trim  sellingprice  PriceRank
0                Ford            Escape    Titanium      230000.0          1
1             Ferrari        458 Italia        Base      183000.0          2
2       Mercedes-Benz           S-Class     S65 AMG      173000.0          3
3         Rolls-Royce             Ghost        Base      171500.0          4
4         Rolls-Royce             Ghost        Base      169500.0          5
...               ...               ...         ...           ...        ...
558794           Ford            Escort  ZX2 Deluxe         100.0     558777
558795           Ford  F-350 Super Duty         XLT           1.0     558796
558796  Mercedes-Benz           E-Class        E500           1.0     558796
558797           Ford      E-Series Van       E-250           1.0     558796
558798          Isuzu             Rodeo          LS           1.0     558796

[558799 rows x 5 columns]

2. Dense Rank

In [44]:
pd.read_sql("""
            select 
            make,
            model,
            trim,
            sellingprice,
            dense_rank() over(
            order by sellingprice desc) 
            as DenseRank
            from vehicle_sales;""", conn)

                 make             model        trim  sellingprice  DenseRank
0                Ford            Escape    Titanium      230000.0          1
1             Ferrari        458 Italia        Base      183000.0          2
2       Mercedes-Benz           S-Class     S65 AMG      173000.0          3
3         Rolls-Royce             Ghost        Base      171500.0          4
4         Rolls-Royce             Ghost        Base      169500.0          5
...               ...               ...         ...           ...        ...
558794           Ford            Escort  ZX2 Deluxe         100.0       1886
558795           Ford  F-350 Super Duty         XLT           1.0       1887
558796  Mercedes-Benz           E-Class        E500           1.0       1887
558797           Ford      E-Series Van       E-250           1.0       1887
558798          Isuzu             Rodeo          LS           1.0       1887

[558799 rows x 5 columns]

3. Row Number By Brand

In [48]:
pd.read_sql("""
            select make,
            model,
            trim,
            sellingprice,
            row_number() over (partition by make
            order by sellingprice desc)
            RowNo
            from vehicle_sales;""", conn)

,make,model,trim,sellingprice,RowNo
0,Acura,MDX,SH-AWD w/Advance and Entertainment Packages,47800.0,1
1,Acura,MDX,SH-AWD w/Advance and Entertainment Packages,47000.0,2
2,Acura,MDX,SH-AWD w/Advance and Entertainment Packages,46500.0,3
3,Acura,MDX,Advance and Entertainment Packages,43800.0,4
4,Acura,MDX,Advance and Entertainment Packages,43800.0,5
...,...,...,...,...,...
558794,Vw,jetta,gls tdi,2500.0,20
558795,Vw,jetta,gls 1.8t,2150.0,21
558796,Vw,jetta,gls 1.8t,1900.0,22
558797,Vw,beetle,gls tdi,1500.0,23
558798,Vw,beetle,gls tdi,500.0,24

4. Top Vehicles Per Brand ( Doubt)

In [53]:
pd.read_sql("""
            with RankedCars as(
            select make,
            model,
            trim,
            sellingprice,
            row_number() over(
            partition by make
            order by sellingprice desc) rn
            from vehicle_sales)
            
            select * from RankedCars
            ;""", conn)

,make,model,trim,sellingprice,rn
0,Acura,MDX,SH-AWD w/Advance and Entertainment Packages,47800.0,1
1,Acura,MDX,SH-AWD w/Advance and Entertainment Packages,47000.0,2
2,Acura,MDX,SH-AWD w/Advance and Entertainment Packages,46500.0,3
3,Acura,MDX,Advance and Entertainment Packages,43800.0,4
4,Acura,MDX,Advance and Entertainment Packages,43800.0,5
...,...,...,...,...,...
558794,Vw,jetta,gls tdi,2500.0,20
558795,Vw,jetta,gls 1.8t,2150.0,21
558796,Vw,jetta,gls 1.8t,1900.0,22
558797,Vw,beetle,gls tdi,1500.0,23
558798,Vw,beetle,gls tdi,500.0,24

Step 14. Case Statements

1. Vehicle Category

In [55]:
pd.read_sql("""
            select sellingprice,
            case
            when sellingprice> 50000 then "Luxury"
            when sellingprice>25000 then "Premium"
            else "Economy"
            end as category
            from vehicle_sales;""", conn)

        sellingprice category
0            21500.0  Economy
1            21500.0  Economy
2            30000.0  Premium
3            27750.0  Premium
4            67000.0   Luxury
...              ...      ...
558794       33000.0  Premium
558795       30800.0  Premium
558796       34000.0  Premium
558797       11100.0  Economy
558798       26700.0  Premium

[558799 rows x 2 columns]

2. Price Status

In [56]:
pd.read_sql("""
            select sellingprice,
            mmr,
            case
            when sellingprice> mmr then "Above MMR"
            when sellingprice < mmr then "Below MMR"
            else "Equal"   
            end as PriceStatus
            from vehicle_sales;""", conn)

        sellingprice      mmr PriceStatus
0            21500.0  20500.0   Above MMR
1            21500.0  20800.0   Above MMR
2            30000.0  31900.0   Below MMR
3            27750.0  27500.0   Above MMR
4            67000.0  66000.0   Above MMR
...              ...      ...         ...
558794       33000.0  35300.0   Below MMR
558795       30800.0  30200.0   Above MMR
558796       34000.0  29800.0   Above MMR
558797       11100.0  15100.0   Below MMR
558798       26700.0  29600.0   Below MMR

[558799 rows x 3 columns]

Step 15. Views

1. Premium Vehicles

In [58]:
pd.read_sql("""
            create view PremiumVehicles as 
            select * from vehicle_sales
            where sellingprice>50000;""", conn)

pd.read_sql("""select * from PremiumVehicles;""", conn)

DatabaseError: Execution failed on sql '
            create view PremiumVehicles as
            select * from vehicle_sales
            where sellingprice>50000;': view PremiumVehicles already exists